import { spawn } from 'child_process';
import { writeFileSync } from 'fs';

const SRC = process.argv[2] || '/home/raktapyas/Downloads/aka.mp4';
const OUT = process.argv[3] || 'assets/bg-art.js';
const COLS = 100, ROWS = 50, FPS = 12;
const GAMMA = 0.55;

const RAMP = ' .,:;i1tfLCG08@';

function grayFrames() {
  return new Promise((res, rej) => {
    const p = spawn('ffmpeg', [
      '-v', 'error', '-i', SRC,
      '-vf', `scale=${COLS}:${ROWS}:flags=area,format=gray`,
      '-f', 'rawvideo', '-'
    ]);
    const b = [];
    p.stdout.on('data', d => b.push(d));
    p.on('close', () => res(Buffer.concat(b)));
    p.on('error', rej);
  });
}

const raw = await grayFrames();
const per = COLS * ROWS;
const n = Math.floor(raw.length / per);
if (!n) throw new Error('no frames decoded from ' + SRC);

const frames = [];
for (let f = 0; f < n; f++) {
  let out = '';
  for (let i = 0; i < per; i++) {
    let v = raw[f * per + i] / 255;
    v = Math.pow(v, GAMMA);
    out += RAMP[Math.min(RAMP.length - 1, Math.floor(v * RAMP.length))];
  }
  const rows = [];
  for (let y = 0; y < ROWS; y++) rows.push(out.slice(y * COLS, y * COLS + COLS));
  frames.push(rows.join('\n'));
}

const js = `/* generated by tools/gen-bg-art.mjs — do not edit
   source: aka.mp4  ${COLS}x${ROWS}  ${n}f @ ${FPS}fps */
window.BG_ART={cols:${COLS},rows:${ROWS},fps:${FPS},frames:${JSON.stringify(frames)}};
`;
writeFileSync(OUT, js);
console.log(`${OUT}: ${n} frames ${COLS}x${ROWS} ${(js.length / 1024).toFixed(0)}KB raw`);
